### ISSUE TITLE
Update Map Marker to include clusters

### ISSUE THREAD

**Issue by tyler-r-smith** [kepler-12/vue-simple-maps#1]
Update Map Marker, so it adds the the marker to a map cluster.
https://developers.google.com/maps/documentation/javascript/marker-clustering

This will allow us to have a large number of markers on the map at once.

**Comment by zackkrida** [comment]
Added in #4, basically the quickest implementation of this possible 🤣 but it works!

**Comment by zackkrida** [comment]
@tyler-r-smith Also published to npm as version "0.0.3"
